openai:
  api_key: YOUR_API_KEY
  api_base: dummy
  api_version: 2023-05-15
  projectBudget: 0.0000001

server:
  forward-headers-strategy: NATIVE
  port: ${APP_PORT:8080}
  servlet:
    contextPath: /${APP_NAME:}

spring:
  datasource:
    url: jdbc:h2:file:${app.location}/gptUnitTestWriter/db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/static/

logging:
  level:
    root: INFO
    com.example.gasc: DEBUG
    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/api/v1/oauth2/simulator/token
      userAuthorizationUri: http://localhost:8080/api/v1/oauth2/simulator/authorize
      clientAuthenticationScheme: form
      clientId: client
      clientSecret: secret
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:8080/api/v1/oauth2/simulator/simulator/me
      tokenInfoUri: http://localhost:8080/api/v1/oauth2/simulator/check_token
